name: Docker Hub

on:
  push:
    branches: [master]
    tags: ["v*"]

jobs:
  docker-publish:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t app .;

      - name: Login into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Define the image tag
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      - name: Check if the tag is a version tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Tag the builded image
        run: docker tag app ${{ secrets.DOCKER_REPO }}:$IMAGE_TAG

      - name: Push image to docker hub
        run: docker push ${{ secrets.DOCKER_REPO }}:$IMAGE_TAG
